### ISSUE TITLE
email notifications setup in pybossa

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1198]
Although there are certain issues related to this topic that seems to be resolved(#115), I could not find crisp documentation on defined steps to setup email notification in pybossa. The email notification is to be setup for password recovery, update selective users about addition of new project or tasks to pybossa, and so on. Please provide steps on configuring pybossa server for sending email notifications considering example of one of mail server (for ex postfix) on ubuntu. Thanks in advance.

**Comment by teleyinex** [comment]
We have not included that configuration for the email server because nowadays is really easy to get your server in a spam list, therefore getting all your emails marked as spam (and in some cases like Outlook or Hotmail accounts the emails are not even delivered). 

For these reasons we decided to include only the basics of setting up the name of the email server like SendGrid, Mandrill, Mailgun, name-yours... as they provide free accounts with enough emails per day and month without all the mentioned problems. Usually all you have to do to set up properly the email is to add a few records to your DNS in order to prove that you have DKIM and SPF fields correctly.

In case you want to avoid this last option, configuring the server should be as simple as this:

    MAIL_SERVER : default ‘localhost’
    MAIL_PORT : default 25
    MAIL_USE_TLS : default False
    MAIL_USE_SSL : default False
    MAIL_DEBUG : default app.debug
    MAIL_USERNAME : default None
    MAIL_PASSWORD : default None
    MAIL_DEFAULT_SENDER : default None
    MAIL_MAX_EMAILS : default None
    MAIL_SUPPRESS_SEND : default app.testing
    MAIL_ASCII_ATTACHMENTS : default False

These config options come directly from flask-mail, the extension that we use to send emails. You have all the documentation [here](https://pythonhosted.org/Flask-Mail/). Is this enough info for you?

**Comment by alejandrodob** [comment]
Hi,

Additionaly, you can use the following configuration to work with a Gmail account:
```
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = 'you@gmail.com'
MAIL_PASSWORD = 'your-password'
```

You may also need to enable [this](https://support.google.com/accounts/answer/6010255) on your Gmail account. Also I do not think this will work for large amounts of email, but for testing and maybe small PyBossa servers it does.

**Comment by dc1520** [comment]
Thanks, this helps

**Comment by dc1520** [comment]
I tried setting up smtp.gmail.com with port 465 and 25 and it didn't worked. I also enabled https://support.google.com/accounts/answer/6010255 on your Gmail account.

**Comment by teleyinex** [comment]
Can you post here the log of the server? We would need to take a look at it.

**Comment by dc1520** [comment]
no message in the logs. On clicking "Reset my password" button, I get message that email has been sent with account recovery instructions

**Comment by teleyinex** [comment]
Just came to my mind. Are you running the background jobs? Because that's how emails are sent, via the background jobs. You can check it going to the admin page, and accessing the background jobs task. There, you should see several queues and some workers listening. Is this running? If you don't see anything running, then, that's what's not working.

You have all the documentation for those workers [here](http://docs.pybossa.com/en/latest/nginx.html#configure-rq-scheduler-and-worker-to-run-with-supervisord).

**Comment by dc1520** [comment]
Thanks @teleyinex . It worked following the docs you've suggested

**Comment by teleyinex** [comment]
Great! Happy to hear that. We're working on improving the documentation, so if you have any suggestions, let us know it.
