### ISSUE TITLE
task_run zip cleanup issue

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1219]
I am observing issue with zipfile created with export to csv/json option; the earlier zipfile created is not cleaned upon export due to which if tasks were completed in stages, zipfile exported later contains old completed tasks. This is also obvious from the code within ../exporter/__init__.py, get_zip() that looks for existing zip and doesnt creates new zip if its existing. Hope I am not missing anything? Attaching code snippet from __init__.py for quick reference,
    def get_zip(self, project, ty):
        """Get a ZIP file directly from uploaded directory
        or generate one on the fly and upload it if not existing."""
        filename = self.download_name(project, ty)
        if not self.zip_existing(project, ty):
            print "Warning: Generating %s on the fly now!" % filename
            self._make_zip(project, ty)

**Comment by therealmarv** [comment]
This is true. ZIP creation is a very time and CPU consuming process, especially if you have more than one user trying to get a ZIP file which can block PyBossa web application.
If you run a production PyBossa installation ZIP files are created with RQ scheduled and worker e.g. every hour or day (it is configurable). This RQ scheduler and worker run outside of the PyBossa web application and let PyBossa stay responsive. Details of this part and how to let PyBossa in a production ready environment are described on this whole page: 

http://docs.pybossa.com/en/latest/nginx.html#configure-rq-scheduler-and-worker-to-run-with-supervisord

The part you are referencing to is a workaround for on the fly ZIP creation which should ideally only happen on corner cases on production. There is no on the fly refreshing of ZIP files. They are refreshed on a timely manner (by RQ scheduler and worker).  So this is by design.

I will leave this bug open for now. Maybe it can be optimized/fine tuned for dev environment.

**Comment by teleyinex** [comment]
@dc1520 are you using the RQ backend jobs to generate those files?

**Comment by dc1520** [comment]
@teleyinex , I am using the regular export mechanism through the webpage when you hit task and select to export task/task_runs in csv/json format

@therealmarv, from UI/webpage option to export task, task_run, should it not cleanup zip from pybossa server location every time it has been successfully downloaded to the client location through web browser and we should call self._make_zip(project, ty) each time in dev?

**Comment by teleyinex** [comment]
So, as @therealmarv said we're avoiding the generation of every zip file via the web interface as it will take too long for different projects (we've projects with more than 150k tasks and and answers). 

Are you using a cloud server for hosting the files, or just your own server? If the answer is the later, then, can you check if you are running the background jobs? You can do it by going to your admin panel on PyBossa, and checking the background jobs. You should have in there something running :-)

If you don't have any, then check this: http://docs.pybossa.com/en/latest/nginx.html#configure-rq-scheduler-and-worker-to-run-with-supervisord

**Comment by teleyinex** [comment]
Please, let us know if this works, otherwise we'll look into how we can solve it :-)

**Comment by dc1520** [comment]
At present, I have test environment in which I am trying to generate zip on the fly. @therealmarv , @teleyinex you're right on setting up production like environment and test if background jobs can generate task_runs for different projects. Hence, the issue stands close at this time. In case I came across the issue with background job task_run zip creation, I will reopen the issue. Thanks for your time

**Comment by teleyinex** [comment]
No problem! Thanks for reporting the issue!
