### ISSUE TITLE
concurrent user access issue with task redundancy

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1280]
Task redundancy set to 1, and more than one users are allowed to contribute to a project, which means only one answer is expected which could be not necessarily from the same user. The real problem occurs when more than one user access the system at the same time. Due to this same task available to multiple users, there could be multiple answers for the same task. Is there any mechanism to avoid multiple answers with redundancy = 1? Something like,
1. user 1 logins, will get task1. this task will be immediately marked as in_progress
2. for user 2, task2 will be provided as task1 is already marked as in_progress
3. user 1 do not submit its task response for 1 hour, the task1 again is marked as new and would be available to other user

**Comment by teleyinex** [comment]
Hi,

No, there's no solution as the only "possible workaround" is to actually lock the available to task, once it has been submitted to a volunteer. However, for how long do you lock the task? Because, for different users, the amount of time to solve a task could vary, so if you lock for an amount of time and the user is not able to solve it, he will get an error, and therefore it will not work. 

As a consequence we send the task to anyone that request the task if the task has not task run saved. This will ensure that at least 1 answer will be saved. When the first task run arrives, the task is then locked (marked as completed) and it will never be in the pool again.

In any case, due to the PYBOSSA plugin system you can create your own scheduler to support what you want without affecting the upstream version of PYBOSSA. Here you've an example https://github.com/PyBossa/plugin-scheduler-template
