### ISSUE TITLE
how to add a new field in to the register.html file?

### ISSUE THREAD

**Issue by luisherrera13** [PyBossa/pybossa#1284]
just a question about were to modify to add a new field in to the register.html file cause i've already done this by editing tath file and adding a new field just the same way the others fields are but when i refresh the page it gets an error so i would like to you to help me with this tanks in advance...

**Comment by teleyinex** [comment]
If you need to modify the register page, you'll have to do a few things:

1.- Modify the form, as we use WTF-forms to render it.
2.- Check the validation, as probably your error is related to that.

Instead of modifying directly the upstream code, I would recommend you to write your own plugin. You can find all the information about plugins in docs.pybossa.com
