### ISSUE TITLE
Allow admins to update results

### ISSUE THREAD

**Issue by alexandermendes** [PyBossa/pybossa#1302]
Hi guys, would it be possible to change the authorisation for results to allow the project owner or admins to update them. I'm essentially trying to set up a single application to help analyse all of our results, which will be created by different users, and the easiest thing to do would be use a single admin API key to do this. If it's not possible I'll try to find another way but thought it was worth asking. Thanks!

**Comment by therealmarv** [comment]
Hi,

can you explain what you mean with "change the authorisation for results". Maybe an example? Just for clarification because I don't know fully what you want to achieve. Thanks.

**Comment by alexandermendes** [comment]
I basically mean allowing administrators to update results for a project, as well as the project owner. Similar to how you have admins or owners being able to update projects and tasks (https://github.com/PyBossa/pybossa/blob/b614361e0847595351d95f589ca34d106d76d2c7/pybossa/auth/task.py#L49-L53).

This would allow us to have write a program that updates results for all of our projects in response to web hooks etc., using just a single admin API key (I've started writing something along those lines here: https://github.com/LibCrowds/libcrowds-analyst). 

Of course there would be other ways to do this but I'm essentially trying to make setting up projects and analysing results as simple as possible for staff that may have little technical knowledge. Hopefully that makes sense!

**Comment by therealmarv** [comment]
ah, ok, now I understand what you want to do. I have good and bad news. Good: Giving granular access with an API and authentication to admins or external privileged users/external servers so that they can modify many aspects of PyBossa with web calls is on our roadmap for this year. Bad: We have no ETA for this and development and architecting this is still in early stages.

My best bet would be creating your own PyBossa Plugin http://docs.pybossa.com/en/latest/plugins.html for this so that you can control task results directly. You can try to make an new blueprint interface/API end point in this plugin which you can call externally (don't forget to secure it).

**Comment by alexandermendes** [comment]
Ok thanks, I've gone the route of just replacing the _update() method in ResultAuth via a plugin, for now.
